# Generated by Django 6.0.6 on 2026-07-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em andamento", "Em andamento"),
                    ("concluída", "Concluída"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
