# Generated by Django 6.0.6 on 2026-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_task_is_completed_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.AddField(
            model_name="task",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
